-- Permanently delete one acceptance and all of its private related records.
-- Storage objects are removed through the Supabase Storage API by the client
-- before this RPC is called; direct SQL deletion would remove metadata only.

drop function if exists public.delete_acceptance_permanently(uuid);

create or replace function public.delete_acceptance_permanently(
  p_acceptance_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_researcher_ids uuid[] := '{}'::uuid[];
  v_attachment_ids uuid[] := '{}'::uuid[];
  v_version_ids uuid[] := '{}'::uuid[];
begin
  if auth.uid() is null or not public.can_manage_acceptances() then
    raise exception 'Not authorized to delete acceptances'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.acceptances
    where id = p_acceptance_id
  ) then
    raise exception 'Acceptance not found'
      using errcode = 'P0002';
  end if;

  select coalesce(array_agg(ar.researcher_id), '{}'::uuid[])
  into v_researcher_ids
  from public.acceptance_researchers ar
  where ar.acceptance_id = p_acceptance_id;

  select coalesce(array_agg(a.id), '{}'::uuid[])
  into v_attachment_ids
  from public.attachments a
  where a.acceptance_id = p_acceptance_id;

  select coalesce(array_agg(v.id), '{}'::uuid[])
  into v_version_ids
  from public.acceptance_versions v
  where v.acceptance_id = p_acceptance_id;

  -- Cascades remove acceptance_researchers, versions and attachment rows.
  delete from public.acceptances
  where id = p_acceptance_id;

  -- A researcher row belongs to this acceptance workflow. Remove it only when
  -- no other acceptance still references it.
  delete from public.researchers r
  where r.id = any(v_researcher_ids)
    and not exists (
      select 1
      from public.acceptance_researchers ar
      where ar.researcher_id = r.id
    );

  -- Permanent deletion means the record must disappear from operational and
  -- audit views as well, including audit entries generated by cascades above.
  delete from public.audit_logs l
  where l.record_id = p_acceptance_id
     or l.record_id = any(v_researcher_ids)
     or l.record_id = any(v_attachment_ids)
     or l.record_id = any(v_version_ids);

  return true;
end;
$$;

revoke all on function public.delete_acceptance_permanently(uuid) from public;
grant execute on function public.delete_acceptance_permanently(uuid) to authenticated;

comment on function public.delete_acceptance_permanently(uuid) is
'Permanently deletes an acceptance and all database records that belong only to it. Private storage objects must be removed through the Storage API before calling this RPC.';
